[tox]
min_version = 4.11.0

envlist =
    py310-lint,
    py311-lint,
    py312-lint,
    black-check,
    py{310,311,312}-Plone{60},

skip_missing_interpreters = True


[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312


[gh-actions:env]
PLONE-VERSION =
    Plone60: Plone60


[testenv]
skip_install = false
usedevelop = true

extras =
    test

commands =
    coverage run -m pytest {posargs}

setenv =
    COVERAGE_FILE=.coverage.{envname}

deps =
    Plone60: -cconstraints_plone60.txt
    coverage
    pytest
    pytest-plone


[testenv:coverage-report]
skip_install = true
usedevelop = True
basepython = python3

deps =
    coverage
    -cconstraints_plone60.txt

setenv =
    COVERAGE_FILE=.coverage

commands =
    coverage erase
    coverage combine
    coverage html
    coverage xml
    coverage report


[lint]
skip_install = true

deps =
    -cconstraints.txt
    isort
    flake8
    flake8-debugger
    flake8-deprecated
    flake8-print
    flake8-todo
    mccabe

commands =
    mkdir -p {toxinidir}/reports/flake8
    flake8 --doctests {toxinidir}/src {toxinidir}/setup.py
    isort --check-only {toxinidir}/src {toxinidir}/setup.py

allowlist_externals =
    mkdir


[testenv:isort-apply]
skip_install = true

deps =
    -cconstraints.txt
    isort

commands =
    isort {toxinidir}/src {toxinidir}/setup.py


[testenv:black-check]
basepython = python3
skip_install = True
deps =
    -cconstraints.txt
    black

commands =
    black --check --diff -v src setup.py


[testenv:black-enforce]
basepython = python3
skip_install = True
deps =
    -cconstraints.txt
    black

commands =
    black -v src setup.py


[testenv:py310-lint]
basepython = python3.10
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}
allowlist_externals = {[lint]allowlist_externals}

[testenv:py311-lint]
basepython = python3.11
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}
allowlist_externals = {[lint]allowlist_externals}

[testenv:py312-lint]
basepython = python3.12
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}
allowlist_externals = {[lint]allowlist_externals}

[testenv:docs]
skip_install = true

deps =
    Sphinx

commands =
    sphinx-build -b html -d _build/docs/doctrees docs _build/docs/html
